apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-xpumanager
spec:
  template:
    spec:
      # hostNetwork should be set true for getting xelink metrics
      hostNetwork: true
      containers:
      - name: xpumd
        env:
        - name: SPDLOG_LEVEL
          value: info
        - name: XPUM_REST_NO_TLS
          value: "1"
        - name: XPUM_EXPORTER_NO_AUTH
          value: "1"
        - name: XPUM_EXPORTER_ONLY
          value: "1"
        - name: XPUM_METRICS
          value: 0-38
        resources:
          limits:
            # maps all GPUs to container
            gpu.intel.com/i915_monitoring: 1
            # map CPU devices to container for PCIe read/write data collection
            # requires registry.gitlab.com/arm-research/smarter/smarter-device-manager:v1.1.2
            # refer to https://gitlab.com/arm-research/smarter/smarter-device-manager for details
            smarter-devices/cpu: 1
            smarter-devices/mem: 1
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          runAsUser: 0
        volumeMounts:
          # for precheck
        - mountPath: /sys/kernel/debug
          name: sysdebug
          # for getting pod resources
        - mountPath: /var/lib/kubelet/pod-resources
          name: kubeletpodres
          # for PCIe read/write data collection
        - mountPath: /pcm/sys/firmware/acpi/tables/MCFG:ro
          name: mcfg
          # for PCIe read/write data collection
        - mountPath: /pcm/proc/bus/pci/
          name: pci
          # for PCIe read/write data collection
        - mountPath: /pcm/proc/sys/kernel/nmi_watchdog
          name: nmiwatchdog
        - name: sockdir
          mountPath: /tmp
      volumes:
      - hostPath:
          path: /sys/kernel/debug
          type: ""
        name: sysdebug
      - hostPath:
          path: /var/lib/kubelet/pod-resources
          type: ""
        name: kubeletpodres
      - hostPath:
          path: /sys/firmware/acpi/tables/MCFG
          type: ""
        name: mcfg
      - hostPath:
          path: /proc/bus/pci/
          type: ""
        name: pci
      - hostPath:
          path: /proc/sys/kernel/nmi_watchdog
          type: ""
        name: nmiwatchdog
      - emptyDir:
          medium: Memory
        name: sockdir
      - hostPath:
          path: /dev/dri
        name: devdri